# IC-GVINS多源融合定位算法配置文件


# ------ laptop
# # 数据集路径
# sequencepath: "/run/timeshift/backup/Datasets/complex_urban/urban38/urban38-pankyo" #laptop
# # 结果输出路径
# # Output directory
# outputpath: "/home/divenire/0_myWorkSpace/Divenire_ws/workingProgram/icgvins_ws/src/IC-GVINS/results" #laptop


#workstation
# 数据集路径
sequencepath: "/home/divenire/0_myWorkSpace/Datasets/complex_urban/urban30/urban30-gangnam" 
# 结果输出路径
# Output directory
outputpath: "/home/divenire/0_myWorkSpace/Divenire_ws/UESTC_papers/chapter3/ic-viwo_ws/src/IC-GVINS/results" 




is_make_outputdir: true
# 时间信息, s
# Time length for GNSS/INS intialization
initlength: 60

# 数据频率, Hz
# IMU sample rate
imudatarate: 100
wheeldatarate: 100
imagedatarate: 10
gnssdatarate: 1


# 考虑地球自转补偿项
# Consider the Earth rotation
iswithearth: true

# 安装参数
# Installation parameters
antlever: [-0.37, 0.008, 0.353]     # 天线杆臂, IMU前右下方向, m  --- GNSS lever-arm in IMU body frame (front-right-down)
odolever: [-0.07, 0, -1.7]  # 里程计杆臂 (odometer lever), IMU前右下方向, m
bodyangle: [0, 0, 0]      # IMU到载体的旋转角 (mouting angles to construct C_b^v), deg

odometer:
    isuseodo: true              # use odometer
    std: [0.1, 0.1, 0.1]   # 里程标准差 (vehicle velocity standard deviation), m/s
    srw: 1                   # 比例因子误差 (odometer scale-factor standard deviation), PPM

# IMU噪声建模参数
# IMU noise parameters
imumodel:
# 0.2 0.5 10 150 1 
# 0.2 1 10 150 1
    arw: 0.2        # deg/sqrt(hr)
    vrw: 0.5        # m/s/sqrt(hr)
    gbstd: 10.0     # deg/hr
    abstd: 150.0     # mGal
    corrtime: 1.0   # hr

# GNSS中断配置
# GNSS outage configurations, the GNSS will not be used after the gnssoutagetime 
#true  not use gnss data
isusegnssoutage: true  


# urban 30:363164
# urban 31: 365403
# urban 32: 366460
#urban 33: 367566
# urban 34: 369015
# urban 35:372687
#urban 36: 372970
# urban 37: 373444
# urban 38:364461.5
# urban 39 :367027.5

gnssoutagetime: 363234

# 固定阈值GNSS抗差
# A fixed threshold (STD, m) for GNSS outlier culling
# 默认5
gnssthreshold: 5

# 是否开启可视化
# Use visualization
is_use_visualization: true

# 跟踪
# Tracking configurations
track_check_histogram: false    # 直方图检查, 避免出现光照变化较大的图像 (Check histogram for drastic illumulation change)
track_min_parallax: 15         # 关键帧最小像素视差 (The minmum parallax in pixels to choose a keyframe)
track_max_interval: 0.5         # 最大的关键帧间隔, 超过则插入观测帧, s (The maximum lenght to choose a observation frame)
track_max_features: 250         # 最大提取特征数量 (The maximum features to detect, may be more or less, see tracking.cc)

# 优化
# Optimization configurations
reprojection_error_std: 1.5         # 像素重投影误差 (The reprojection error std for optimizition and outlier culling)
optimize_windows_size: 15           # 滑动窗口大小 (The size of the sliding window, number of the keyframes )
optimize_num_iterations: 20         # 优化迭代次数 (The iterations in total)
# TODO 好像不优化外参会更好一点。先这样吧
optimize_estimate_extrinsic: false   # 是否估计相机和IMU的外参 (Estimate the extrinsic)
optimize_estimate_td: true          # 否估计相机和IMU之间的时间间隔 (Estimate the time delay)

# Camera parameters
cam0:
    # 内参 [fx, fy, cx, cy(, skew)]
    # Intrinsic parameters, pinhole model
    intrinsic:
        [
            8.1690378992770002e+02,
            8.1156803828490001e+02,
            6.0850726281690004e+02,
            2.6347599764440002e+02,
            5.0510166700000003e-01,
        ]

    # 畸变参数 [k1, k2, p1, p2(, k3)]
    # Distortion parameters
    distortion:
        [
            -5.6143027800000002e-02,
            1.3952563200000001e-01,
            -1.2155906999999999e-03,
            -9.7281389999999998e-04,
            -8.0878168799999997e-02,
        ]

    # 图像分辨率
    # Resolution
    resolution: [1280, 560]

    # 相机IMU外参 (Camera-IMU extrinsic)
    # Pb = q_b_c * Pc + t_b_c
    # q (x, y, z, w)
    q_b_c: [0.49452151768306785, 0.4977818081111032, 0.5055845943507494, 0.5020417891144757]
    t_b_c: [1.71239, -0.247401, 0.11589]

    # IMU和相机时间延时 (The time delay between the IMU and camera)
    # t_i = t_c + td
    td_b_c: 0.0
